### PR TITLE
Flat pages/children method

### PR DESCRIPTION
**Pull request by jongacnik**
This implements the enoki tools `children()` method to match top-level keys as described in https://github.com/enokidotsite/enoki/issues/15#issuecomment-381749978

Matching is done using a regular expression so we can match *direct* children:

```js
new RegExp('^\/parent\/[^\/]+\/?$')
```

```bash
/parent # will not match
/parent/child # will match
/parent/child/grandchild # will not match
```

Additionally, this implementation makes an assumption that the `url` field within a page entry in state is `===` to the key of that page in `state.content`.

### CODE REVIEW

**Comment by jongacnik** [comment]
Actually this regex needs a minor adjustment to correctly match children of root `/`. Might need to get to this tomorrow.

**Comment by jongacnik** [comment]
Since in some ways this approach is meant to remove the need for the `pages` property from a page entry in state, it might also be worth looking at the other references to `pages` in the `find()`, `isFirst()`, and `isLast()` methods / these methods might also indicate why an only-flat structure might *not* be best?

**Comment by jongacnik** [comment]
After sleeping on this, still wondering if 👍 or 👎. Just in the sense of having that nested `pages` prop allows for the scoped `find()` as well as the `isFirst()` `isLast()` methods (I know that you cant rely on object ordering 100%, but still...). Open for thoughts!

**Comment by jondashkyle** [comment]
I think we can simply use the updated `children` utility within `find`, and compare against that object instead of the `state.content`. Same goes for `isFirst` and `isLast`, which currently aren’t public as the ordering can be messed up, like you mentioned.

**Comment by jondashkyle** [comment]
Going to merge this into a fresh branch, then abstract into `nanopage`.

**Pull request merged**
